/*
Copyright 2020 The Sample Operator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	scheme "kubevirt.io/controller-lifecycle-operator-sdk/examples/sample-operator/pkg/api-client/clientset/versioned/scheme"
	v1alpha1 "kubevirt.io/controller-lifecycle-operator-sdk/examples/sample-operator/pkg/apis/sample/v1alpha1"
)

// SampleConfigsGetter has a method to return a SampleConfigInterface.
// A group's client should implement this interface.
type SampleConfigsGetter interface {
	SampleConfigs() SampleConfigInterface
}

// SampleConfigInterface has methods to work with SampleConfig resources.
type SampleConfigInterface interface {
	Create(ctx context.Context, sampleConfig *v1alpha1.SampleConfig, opts v1.CreateOptions) (*v1alpha1.SampleConfig, error)
	Update(ctx context.Context, sampleConfig *v1alpha1.SampleConfig, opts v1.UpdateOptions) (*v1alpha1.SampleConfig, error)
	UpdateStatus(ctx context.Context, sampleConfig *v1alpha1.SampleConfig, opts v1.UpdateOptions) (*v1alpha1.SampleConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SampleConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SampleConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SampleConfig, err error)
	SampleConfigExpansion
}

// sampleConfigs implements SampleConfigInterface
type sampleConfigs struct {
	client rest.Interface
}

// newSampleConfigs returns a SampleConfigs
func newSampleConfigs(c *SampleV1alpha1Client) *sampleConfigs {
	return &sampleConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the sampleConfig, and returns the corresponding sampleConfig object, and an error if there is any.
func (c *sampleConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SampleConfig, err error) {
	result = &v1alpha1.SampleConfig{}
	err = c.client.Get().
		Resource("sampleconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SampleConfigs that match those selectors.
func (c *sampleConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SampleConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SampleConfigList{}
	err = c.client.Get().
		Resource("sampleconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sampleConfigs.
func (c *sampleConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("sampleconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a sampleConfig and creates it.  Returns the server's representation of the sampleConfig, and an error, if there is any.
func (c *sampleConfigs) Create(ctx context.Context, sampleConfig *v1alpha1.SampleConfig, opts v1.CreateOptions) (result *v1alpha1.SampleConfig, err error) {
	result = &v1alpha1.SampleConfig{}
	err = c.client.Post().
		Resource("sampleconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sampleConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a sampleConfig and updates it. Returns the server's representation of the sampleConfig, and an error, if there is any.
func (c *sampleConfigs) Update(ctx context.Context, sampleConfig *v1alpha1.SampleConfig, opts v1.UpdateOptions) (result *v1alpha1.SampleConfig, err error) {
	result = &v1alpha1.SampleConfig{}
	err = c.client.Put().
		Resource("sampleconfigs").
		Name(sampleConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sampleConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *sampleConfigs) UpdateStatus(ctx context.Context, sampleConfig *v1alpha1.SampleConfig, opts v1.UpdateOptions) (result *v1alpha1.SampleConfig, err error) {
	result = &v1alpha1.SampleConfig{}
	err = c.client.Put().
		Resource("sampleconfigs").
		Name(sampleConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sampleConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the sampleConfig and deletes it. Returns an error if one occurs.
func (c *sampleConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("sampleconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sampleConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("sampleconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched sampleConfig.
func (c *sampleConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SampleConfig, err error) {
	result = &v1alpha1.SampleConfig{}
	err = c.client.Patch(pt).
		Resource("sampleconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
